name: ssh command
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: |
          scp -i ${{ secrets.DEV_SSHE_SSH_KEY }} ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }}:/app/deploy_test.sh /tmp/deploy_test.sh
          chmod 700 /tmp/deploy_test.sh
          ssh ${{ steps.ssh.outputs.SERVER }} bash /tmp/deploy_test.sh natsuki_fujii
